[package]
name = "chess_game"
version = "1.0.0"
edition = "2021"

[dependencies]
rand = "0.8.5"

[dev-dependencies]
criterion = {version = "0.5.1", features = ["html_reports"]}


[[bench]]
name = "test_bench"
harness = false